name: ci

on: ["push","pull_request"]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            bundle: nsis
          - os: macos-latest
            target: aarch64-apple-darwin
            bundle: dmg
          - os: macos-latest
            target: x86_64-apple-darwin
            bundle: dmg
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bundle: appimage
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Update Rust Toolchain
        run: rustup update 
      - name: Install Rust Target
        run: rustup target add ${{matrix.target}}
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Pnpm install
        run: pnpm install
      - name: Install Tauri Dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install libwebkit2gtk-4.0-dev \
            build-essential \
            curl \
            wget \
            file \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev
      - name: Tauri build
        uses: tauri-apps/tauri-action@v0
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tauriScript: pnpm tauri
          args: --target ${{ matrix.target }} -b ${{ matrix.bundle }}
          
      - name: Upload Macos Artifacts
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: target/${{ matrix.target }}/release/bundle/dmg/*.dmg
          if-no-files-found: error

      - name: Upload Windows Artifacts
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: target/${{ matrix.target }}/release/bundle/nsis/*.exe
          if-no-files-found: error